### ISSUE TITLE
Make it clearer which parts are from the original library

### ISSUE THREAD

**Issue by raphaelm** [opacapp/multiline-collapsingtoolbar#1]
@johan12345, not only out of curiosity, but mostly to make this library easier to maintain with future versions of the support library -- could you think of a way to make it more clear which parts of the code are created by you and which are from Android? I could think of a suitalble subclassing pattern or simple clear comments inside the code.

**Comment by johan12345** [comment]
If you look at https://github.com/johan12345/opacclient/compare/35d1d9f...7d2150b, you see the only things I changed were inside the `CollapsingTextHelper` class (there are some other changes in this diff, but they belong to files outside this library).
In the first commit https://github.com/johan12345/opacclient/commit/35d1d9fc9e746f2b06b58c6d262a23607b9acedd I changed the `package` declaration in all the copied files and maybe I also needed to add and/or change some imports in the copied files to make them compile outside the `android.support.design` package, but that should be the only changes outside the `CollapsingTextHelper` class.

Making the `CollapsingTextHelper` changes inside a subclass is difficult because parts of them are inside `private` methods, so I would need to do it one of these ways:

* Change `private` keywords to `protected` in the original `CollapsingTextHelper` to be able to override methods in a subclass (`MultilineCollapsingTextHelper`) -> the `CollapsingTextHelper` would not be 100% the same file as in the Support Library
* Don't change anything in the original `CollapsingTextHelper` class and override all usages of the changed private methods from public methods in `MultilineCollapsingTextHelper` to use the changed implementation -> would probably result in a lot of duplicate code
* Use comments to mark the places where I changed things, like you suggested

**Comment by raphaelm** [comment]
Okay, then forget about subclassing and just drop some comments in there for the future.

**Comment by johan12345** [comment]
Comments were added in 3b53ead5.
