### ISSUE TITLE
Affecting another native colapsing toolbar

### ISSUE THREAD

**Issue by bambolz** [opacapp/multiline-collapsingtoolbar#16]
when I also used native colapsing toolbar seems it affected by this library (colapsing text appearance hidden) so i must set for appearance on each native Colapsing toolbar.

**Comment by johan12345** [comment]
@bambolz Thank you for the bug report. Could you please post some example code and maybe screenshots to help us understand and reproduce the problem?

**Comment by bambolz** [comment]
after trying again and changed to 'com.android.support:appcompat-v7:24.0.0' it's seems pretty normal, so I thinks the bug is on 'com.android.support:appcompat-v7:24.1.0' sorry

**Comment by johan12345** [comment]
Indeed, we haven't yet updated the library to be compatible with version 24.1.0, as it was just released two days ago. I created a corresponding issue #17.

**Comment by johan12345** [comment]
While the issue you faced was probably related to [this](https://www.reddit.com/r/androiddev/comments/4u0gw1/support_library_2411_released/d5lusg4) and is fixed with support library 24.1.1, I have now also updated this library to use the newest support library version. It will be included in the next release.

**Comment by raphaelm** [comment]
1.2.2 is released :)
