### ISSUE TITLE
Expanded Title line spacing

### ISSUE THREAD

**Issue by ButterRhopa** [opacapp/multiline-collapsingtoolbar#29]
How to set the line spacing(like lineSpacingExtra or lineSpacingMultiplier) of expanded title? I am a new to Android and the project is too complex for me......So i did not find the answer

thanks a lot.

**Comment by johan12345** [comment]
Currently, this is not possible because we have not added a method that allows to set these values. Instead, the values are hard-coded to `lineSpacingMultiplier = 1` and `lineSpacingExtra = 0`.

It should be quite straightforward to add two methods for setting these values both to `CollapsingTextHelper` and then to `CollapsingToolbarLayout` (where the latter just needs to call the corresponding methods in `CollapsingTextHelper`). The point where the values are currently hard-coded is [here](https://github.com/opacapp/multiline-collapsingtoolbar/blob/master/multiline-collapsingtoolbar/src/main/java/net/opacapp/multilinecollapsingtoolbar/CollapsingTextHelper.java#L749).

Would you like to fork our repository and submit a pull request to add these methods?
