### ISSUE TITLE
Update library to Support Library version 28.0.0

### ISSUE THREAD

**Issue by PattaFeuFeu** [opacapp/multiline-collapsingtoolbar#60]
https://developer.android.com/topic/libraries/support-library/revisions

The new Support Library version 28.0.0 is out.

From what I can see in the changelogs, it doesn’t look like any changes might affect this library.

**Comment by marchy** [comment]
Anyone able to take this on?

**Comment by johan12345** [comment]
As discussed in #61 and #63, this update is not trivial due to some changes in Android 9 where a lot of classes are library-private and this is now enforced by the system. We would need to copy a lot of additional classes to this library so that they are accessible and maintain them with future updates. I only see one sensible ways to go forward with this:

- Create a fork of the whole [Material Components Android](https://github.com/material-components/material-components-android) library and implement our changes there
- And try to make Google merge these changes in their library (see https://github.com/material-components/material-components-android/issues/6).

**Comment by johan12345** [comment]
We have now opened a PR at https://github.com/material-components/material-components-android/pull/413 and hope this feature can then be merged into the main Material Components library.
