### ISSUE TITLE
Can't link to library from my project

### ISSUE THREAD

**Issue by RicoGeoibour** [opacapp/multiline-collapsingtoolbar#7]
I get a connection refused from Android studio when trying to import de the project in my build.gradle. do you know where it can comes from ? thanks

**Comment by johan12345** [comment]
Do you have the `jcenter()` line in your top-level build.gradle file, similar to [this one](https://github.com/opacapp/opacclient/blob/master/opacclient/build.gradle) ?

Do you encounter the same issue when importing other 3rd party libraries hosted on JCenter (excluding the Android Support Library, which Android Studio stores locally instead of downloading it)?

**Comment by RicoGeoibour** [comment]
Seems to be what was missing. Many thanks, works like a charm now.
